"""Prompts for various security testing agents."""
from .prompts import (
    ROLE_PREVALIDATION_PROMPT,
    FUZZ_VERDICT_PROMPT,
    ROLE_GENERATION_PROMPT,
    INJECTION_ANALYSIS_PROMPT
)

__all__ = [
    'ROLE_PREVALIDATION_PROMPT',
    'FUZZ_VERDICT_PROMPT',
    'ROLE_GENERATION_PROMPT',
    'INJECTION_ANALYSIS_PROMPT'
]